testing

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,12 +1,38 @@
 #!/bin/sh
 
-STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".tsx\{0,1\}$")
+STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$")
+NG_STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".tsx\{0,1\}$")
 
-if [[ "$STAGED_FILES" = "" ]]; then
+if [[ "$STAGED_FILES" = "" && "$NG_STAGED_FILES" = "" ]]; then
   exit 0
 fi
 
 PASS=true
+
+if [[ "$STAGED_FILES" != "" ]]; then
+  echo "\nValidating Javascript:\n"
+
+  # Check for eslint
+  which eslint &> /dev/null
+  if [[ "$?" == 1 ]]; then
+    echo "\t\033[41mPlease install ESlint\033[0m"
+    exit 1
+  fi
+
+  for FILE in $STAGED_FILES
+  do
+    eslint "$FILE"
+
+    if [[ "$?" == 0 ]]; then
+      echo "\t\033[32mESLint Passed: $FILE\033[0m"
+    else
+      echo "\t\033[41mESLint Failed: $FILE\033[0m"
+      PASS=false
+    fi
+  done
+
+  echo "\nJavascript validation completed!\n"
+fi
 
 echo "\nValidating Typescript:\n"
 
@@ -17,7 +43,7 @@ if [[ "$?" == 1 ]]; then
   exit 1
 fi
 
-for FILE in $STAGED_FILES
+for FILE in $NG_STAGED_FILES
 do
   eslint "$FILE"
 
