testing

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,66 +1,43 @@
 #!/bin/sh
 
-STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$")
-NG_STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".tsx\{0,1\}$")
+STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".tsx\{0,1\}$")
 
-if [[ "$STAGED_FILES" = "" && "$NG_STAGED_FILES" = "" ]]; then
+if [[ "$STAGED_FILES" = "" ]]; then
   exit 0
 fi
 
 PASS=true
 
-if [[ "$STAGED_FILES" != "" ]]; then
-  echo "\nValidating Javascript:\n"
+# Prettify all selected files
+echo "\nprettifying files\n"
+echo "$STAGED_FILES" | xargs ./node_modules/.bin/prettier --ignore-unknown --write
 
-  # Check for eslint
-  which eslint &> /dev/null
-  if [[ "$?" == 1 ]]; then
-    echo "\t\033[41mPlease install ESlint\033[0m"
-    exit 1
+# Add back the modified/prettified files to staging
+echo "$STAGED_FILES" | xargs git add
+echo "\nprettifying complete"
+
+echo "\nValidating Typescript:\n"
+
+# Check for eslint
+which eslint &> /dev/null
+if [[ "$?" == 1 ]]; then
+  echo "\t\033[41mPlease install ESlint\033[0m"
+  exit 1
+fi
+
+for FILE in $STAGED_FILES
+do
+  eslint "$FILE"
+
+  if [[ "$?" == 0 ]]; then
+    echo "\t\033[32mESLint Passed: $FILE\033[0m"
+  else
+    echo "\t\033[41mESLint Failed: $FILE\033[0m"
+    PASS=false
   fi
+done
 
-  for FILE in $STAGED_FILES
-  do
-    eslint "$FILE"
-
-    if [[ "$?" == 0 ]]; then
-      echo "\t\033[32mESLint Passed: $FILE\033[0m"
-    else
-      echo "\t\033[41mESLint Failed: $FILE\033[0m"
-      PASS=false
-    fi
-  done
-
-  echo "\nJavascript validation completed!\n"
-fi
-
-
-if [[ "$NG_STAGED_FILES" != "" ]]; then
-  echo "\nValidating Angular project:\n"
-
-  # Prettify all selected files
-  echo "\nprettifying files\n"
-  echo "$NG_STAGED_FILES" | xargs ./app-v2/node_modules/.bin/prettier --ignore-unknown --write
-
-  # Add back the modified/prettified files to staging
-  echo "$NG_STAGED_FILES" | xargs git add
-  echo "\nprettifying complete"
-
-  for FILE in $NG_STAGED_FILES
-  do
-    eslint "$FILE"
-
-    if [[ "$?" == 0 ]]; then
-      echo "\t\033[32mESLint Passed: $FILE\033[0m"
-    else
-      echo "\t\033[41mESLint Failed: $FILE\033[0m"
-      PASS=false
-    fi
-  done
-
-  echo "\Angular project validation completed!\n"
-fi
-
+echo "\Typescript validation completed!\n"
 
 if ! $PASS; then
   echo "\033[41mCOMMIT FAILED:\033[0m Your commit contains files that should pass ESLint but do not. Please fix the ESLint errors and try again.\n"
@@ -69,4 +46,4 @@ else
   echo "\033[42mCOMMIT SUCCEEDED\033[0m\n"
 fi
 
-exit $?npx lint-staged
+exit $?
