testing

diff --git a/.github/workflows/eslint.yml b/.github/workflows/eslint.yml
--- a/.github/workflows/eslint.yml
+++ b/.github/workflows/eslint.yml
@@ -41,12 +41,14 @@ jobs:
           for file in "${filesArray[@]}"
           do
             if [[ $file == *.js || $file == *.ts ]]; then
-              echo "Running ESLint on $file"
               npx eslint "$file"
-              echo "last command resutl ===== $?"
               if [[ "$?" != 0 ]]; then
-                echo "ESLint failed on file: $file"
                 eslintFailed=true
               fi
             fi
           done
+
+          if [ "$eslintFailed" = true ]; then
+            echo "ESLint check failed."
+            exit 1
+          fi
